// @ts-check
import rsEslint from "@rebeccastevens/eslint-config";

export default rsEslint(
  {
    projectRoot: import.meta.dirname,
    mode: "library",
    typescript: {
      unsafe: "off",
    },
    formatters: true,
    functional: "lite",
    jsonc: true,
    markdown: true,
    stylistic: true,
    yaml: true,
    ignores: [
      // Autogenerated files
      "src/exponents.ts",
      "src/units/converters/prefixes.ts",
      "src/units/modifiers/prefixes.ts",
    ],
  },
  {
    rules: {
      "ts/naming-convention": "off",
    },
  },
);
