name: Check Generated Files

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  check_generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run generate-files
      - run: git diff-index HEAD --
