name: Update Docs

on:
  push:
    tags:
      # https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string -- github doesn't like this regex??
      - v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)
      - v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-|\+)([a-zA-Z0-9]|-|+|\.)*

permissions:
  contents: write
  id-token: write

concurrency:
  group: Update Docs
  cancel-in-progress: false

jobs:
  update_docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout the docs
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Set Package Json Version
        env:
          TAG: ${{ github.ref_name }}
        run: npm version --no-git-tag-version "${TAG#v}"

      - uses: ./.github/actions/prepare

      - name: Build
        run: pnpm run build

      - name: Build docs
        run: pnpm run docs

      - name: Save docs
        run: tar -cvf /tmp/docs.tar ./docs/generated

      - name: checkout the docs
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          clean: false #  doesn't seem to work?? Hence use of tar.

      - uses: ./.github/actions/prepare

      - name: Remove old docs
        run: rm -rf ./docs/generated

      - name: Restore docs
        run: |
          mkdir -p ./docs/generated
          tar -xf /tmp/docs.tar ./docs/generated -C ./docs/generated

      - name: Commit
        run: |
          git add -f docs/generated
          git commit -m "docs: update documentation"
          git push
        continue-on-error: true
