name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  issues: write
  pages: write
  pull-requests: write

concurrency:
  group: Release
  cancel-in-progress: false

jobs:
  lint_js:
    uses: ./.github/workflows/lint-js.yml
  lint_knip_prod:
    uses: ./.github/workflows/lint-knip-prod.yml
  lint_markdown:
    uses: ./.github/workflows/lint-markdown.yml
  lint_spelling:
    uses: ./.github/workflows/lint-spelling.yml
  lint_prettier:
    uses: ./.github/workflows/lint-prettier.yml
  test_js:
    uses: ./.github/workflows/test-js.yml
  test_types:
    uses: ./.github/workflows/test-types.yml
  type_check:
    uses: ./.github/workflows/type-check.yml

  release:
    needs:
      - lint_js
      - lint_knip_prod
      - lint_markdown
      - lint_spelling
      - lint_prettier
      - test_js
      - test_types
      - type_check
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: ./.github/actions/prepare

      - name: Build
        run: pnpm run build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  release_docs:
    needs: release
    if: needs.release.outputs.new_release_published == 'true'
    uses: ./.github/workflows/release-docs.yml
