name: Test Types

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test_types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/prepare
      - run: pnpm run generate-files
      - run: pnpm run build
      - run: pnpm run test:types
